### ISSUE TITLE
Keep links when translating

### ISSUE THREAD

**Issue by dxcore35** [friebetill/obsidian-deepl#1]
If there is standard links in text let say from english to spanish:

`[[Mathematics]] is a [peer-reviewed](https://www.mdpi.com/editorial_process), open-access journal which provides an advanced forum for studies related to mathematics, and is published semimonthly online by MDPI.`

The links will be translated:

- `[[Mathematics|Matemáticas]]`
- `[[revisado por pares]](https://www.mdpi.com/editorial_process)
`

**Comment by friebetill** [comment]
Unfortunately, [DeepL does not offer the possibility](https://www.deepl.com/docs-api/translate-text/translate-text/) of such fine configuration.

In addition I translated your text into Spanish and got this version:

`[[Mathematics]] es una revista [revisada por pares](https://www.mdpi.com/editorial_process), de acceso abierto, que proporciona un foro avanzado para los estudios relacionados con las matemáticas, y se publica semestralmente en línea por MDPI`

In my opinion, this the best case. Link texts are translated and link urls are not translated.

**Comment by dxcore35** [comment]
It is not feature of the DeepL but, pre-processing of the text that is coming from Obsidian environment should be done before sending the text into DeepL and then replacing the links back. It a quite work to do but when it is done you can simply add button for example in note that will show the note in different language, where all is in different language and links are preserved. 

_Imagine somebody translating text where text have 50 [[links]] all these links = file names, needs to be translated. Otherwise the text is a combination of original language and translated language._  


I will not close this issue, at least because it was not resolved.

**Comment by friebetill** [comment]
A good point with the pre-processing! 

I have now reconfirmed that the links are translated. I'll will try to fix it now

**Comment by friebetill** [comment]
I have released a new version where the links are not translated. If there are any problems, let me know and I'll open the issue again!
