### ISSUE TITLE
Insert translation after the original text

### ISSUE THREAD

**Issue by friebetill** [friebetill/obsidian-deepl#3]
Original message by Noah
> For me, however, the plugin would be even more useful if it would insert the translation of the text directly after the original text. I would therefore like to have an option in the settings that could give you the choice of whether the text selected for translation should be deleted and replaced with the translated text or whether the translation should be appended directly to the original text. Perhaps this could even be developed into two separate commands so that the workflow can be even faster and you can decide on a case-by-case basis how the text should be translated.

**Comment by friebetill** [comment]
Thank you, Noah, for submitting your request and for presenting your suggestion in a clear and concise manner. Currently, I am occupied, but I will consider finding an effective solution and implementing it if I determine that there is a widespread need for it. I will keep this issue open and will take action if it receives 10 likes.

**Comment by dario-baumberger** [comment]
I have opened a pull request (https://github.com/friebetill/obsidian-deepl/pull/4) that includes this feature, among others. 

I have implemented it in such a way that the translation is inserted directly (with a space) after the selection. You have to select the language yourself by suggestion modal. Does this work for you? If the statically stored language from the settings is to be used, I can gladly add this. 

However, I will wait for feedback from @friebetill first.

**Comment by friebetill** [comment]
Closed by #4
