### ISSUE TITLE
Request to add Korean to TARGET LANGUAGE

### ISSUE THREAD

**Issue by JupiterWolfram** [friebetill/obsidian-deepl#5]
[Request to add Korean to TARGET LANGUAGE]

Hello. Thank you for creating such a great plugin.
I got the API and tried to test it, but Korean is not in the selection list.
Please add Korean to the list.

I really appreciate any help you can provide.

**Comment by gangjeuk** [comment]
I added pull request for Korean support. (link down below)

https://github.com/friebetill/obsidian-deepl/pull/6

한국어 지원을 위한 리퀘스트를 넣었어요!
혹시 필요하시면 바뀐 부분만 넣으시면 작동하실 거예요!!

**Comment by gangjeuk** [comment]
> [Request to add Korean to TARGET LANGUAGE]
> 
> Hello. Thank you for creating such a great plugin. I got the API and tried to test it, but Korean is not in the selection list. Please add Korean to the list.
> 
> I really appreciate any help you can provide.

I added pull request for Korean support. (link down below)

https://github.com/friebetill/obsidian-deepl/pull/6

한국어 지원을 위한 리퀘스트를 넣었어요!
혹시 필요하시면 바뀐 부분만 넣으시면 작동하실 거예요!!

**Comment by friebetill** [comment]
Closed by #6.
